---
# tasks file for create-namespace

- name: Create new namespace
  shell: |
    oc get namespace {{namespace}}
  register: get_namespace_output
  tags: always
  ignore_errors: true

- name: Create new namespace
  shell: |
    oc create namespace {{namespace}}
  register: create_namespace_output
  when: (get_namespace_output.rc != 0)
  tags: always

- name: Change namespace if created
  shell: |
    oc project {{namespace}}
  register: project
  when: (get_namespace_output.rc == 0) or (create_namespace_output != 0)
  tags: always